-- Placeholder mints and PDAs. Replace with the deployed program's values.
insert into public.vaults (symbol, xstock_mint, vault_pubkey, tier, share_mint) values
  ('MSTR',  'PLACEHOLDER_MSTRx_MINT',  'PLACEHOLDER_VAULT_MSTR',  3, 'PLACEHOLDER_SHARES_MSTR'),
  ('SPY',   'PLACEHOLDER_SPYx_MINT',   'PLACEHOLDER_VAULT_SPY',   0, 'PLACEHOLDER_SHARES_SPY'),
  ('GOOGL', 'PLACEHOLDER_GOOGLx_MINT', 'PLACEHOLDER_VAULT_GOOGL', 0, 'PLACEHOLDER_SHARES_GOOGL'),
  ('QQQ',   'PLACEHOLDER_QQQx_MINT',   'PLACEHOLDER_VAULT_QQQ',   0, 'PLACEHOLDER_SHARES_QQQ'),
  ('TSLA',  'PLACEHOLDER_TSLAx_MINT',  'PLACEHOLDER_VAULT_TSLA',  1, 'PLACEHOLDER_SHARES_TSLA'),
  ('NVDA',  'PLACEHOLDER_NVDAx_MINT',  'PLACEHOLDER_VAULT_NVDA',  1, 'PLACEHOLDER_SHARES_NVDA'),
  ('CRCL',  'PLACEHOLDER_CRCLx_MINT',  'PLACEHOLDER_VAULT_CRCL',  3, 'PLACEHOLDER_SHARES_CRCL'),
  ('HOOD',  'PLACEHOLDER_HOODx_MINT',  'PLACEHOLDER_VAULT_HOOD',  3, 'PLACEHOLDER_SHARES_HOOD'),
  ('AAPL',  'PLACEHOLDER_AAPLx_MINT',  'PLACEHOLDER_VAULT_AAPL',  2, 'PLACEHOLDER_SHARES_AAPL')
on conflict (symbol) do nothing;
